# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nueva_entrada', models.TextField()),
                ('titulo', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, height_field='heigth_field', null=True, upload_to=b'', width_field='width_field')),
                ('heigth_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('firma', models.CharField(max_length=200)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Genero')),
            ],
        ),
    ]
