# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170903_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
