# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name_image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
