# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 00:44
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_name_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='nueva_entrada',
            field=tinymce.models.HTMLField(),
        ),
    ]
