# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-11 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20170904_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='nueva_entrada',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='post',
            name='comentarios',
            field=models.ManyToManyField(to='post.Comentario'),
        ),
    ]
