# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-24 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20171224_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
