# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-27 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20171224_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name_image',
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
