# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-27 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20171227_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='post',
            name='imagen2',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen3',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen4',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
